services:
  postgres:
    image: postgres:latest
    container_name: nocodb-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - nocodb-net

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NC_DB: "pg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    depends_on:
      - postgres
    networks:
      - nocodb-net

volumes:
  pgdata:

networks:
  nocodb-net: